### ISSUE TITLE
Where is label.txt?

### ISSUE THREAD

**Issue by Billy1900** [lunpin1101/dablog#1]
First, I want to ask: what is label.txt and how can I find it?

```shell
Traceback (most recent call last):                       ]   0% Elapsed Time: 0:00:00 ETA:  --:--:--
  File "exp-sosp2009.py", line 911, in <module>
    main()
  File "exp-sosp2009.py", line 64, in main
    op(args)
  File "exp-sosp2009.py", line 124, in SequentialAnomalyDetection
    for line in open(args.label, 'r'):
FileNotFoundError: [Errno 2] No such file or directory: 'label.txt'
```

Second, I cannot find the SOSP2009 dataset with your link. @lunpin1101

**Comment by lunpin1101** [comment]
Please find the SOSP dataset at http://people.iiis.tsinghua.edu.cn/~weixu/sospdata.html
You will need to preprocess the data on your own.  Split the dataset by block IDs.  Each line in label.txt is of format "[0 or 1] [block_id]".  Include in label.txt only the blocks you used in training or testing.  Please revisit https://github.com/lunpin1101/dablog/tree/main/data for examples of how postprocessed data should look like.  I hope this helps.

**Comment by Billy1900** [comment]
Does that mean 0 denotes normal or abnormal?

**Comment by lunpin1101** [comment]
I use the same notation in SOSP dataset.  "0"s indicate normal sessions.

https://github.com/lunpin1101/dablog/blob/main/exp-sosp2009.py#L104
```
    for line in open (args.label, 'r'):
        count += 1
        bar.update (count)
        label, block = line.split ()
        if label == '0': normals.append (block)
        else: abnormals.append (block)
```
