### ISSUE TITLE
SOSP 2009 dataset split

### ISSUE THREAD

**Issue by Billy1900** [lunpin1101/dablog#2]
From the raw dataset, I get `HDFS.log` dataset which contains all of the `block_ID`. How do you split the data into different log files according to different block ID?

**Comment by lunpin1101** [comment]
I lost the split script for SOSP dataset, so you need to implement one for yourself.  Here's an example split script for UNSW-NB15 dataset. https://github.com/lunpin1101/dablog/blob/main/unswnb15/split.py
